name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Grant execute permissions for gradlew
        working-directory: Todo
        run: chmod +x gradlew

      - name: Build & Run Unit Tests
        working-directory: Todo
        run: ./gradlew build  # assemble + checks

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: built-apks
          path: Todo/app/build/outputs/apk/**/*.apk

      - name: Upload lint report
        uses: actions/upload-artifact@v4
        with:
          name: lint.html
          path: Todo/app/build/reports/lint-results-debug.html

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: Todo/app/build/reports/tests/testDebugUnitTest/